services:

  exp_engine:
    # Use the pre-built image from Github Container Registry
    image: ghcr.io/extremexp-horizon/exp-engine:latest
    # Uncomment the following lines to build the image locally
    # build: ./exp_engine
    container_name: exp-eng-service
    ports:
      - '5556:5556'
    networks:
      - my_net
    volumes:
      - ../eexp_workspace/code-server:/exp_engine/workspace/:wr # Shared Directory (Stores user/(experiment|workflow|task|dependencies) files) between Portal, Experimentation Engine and ExtremeXP-IDE
      - eexp_config.py:/exp_engine/eexp_config.py # Configuration file for Experimentation Engine

networks:
  my_net:
    name: extremexp_network
    external: true
